photo_3885@09-12-2024_02-49-31.jpg:
  name: photo_3885@09-12-2024_02-49-31.jpg
  path: 测试/testdir/photo_3885@09-12-2024_02-49-31.jpg
  md5: 3e28ce6cdb1d640b881b2c0ea1722723
test.md:
  name: test.md
  path: 测试/testdir/test.md
  md5: 64b02b00d9b9d1a2e257f7c26149ccfe
wqy-microhei.ttc:
  name: wqy-microhei.ttc
  path: wqy-microhei.ttc
  md5: 966af48e02884546677a2f762f6725b9
失落的奧德賽_千年之夢_永遠的旅人_永遠を旅する者_ロストオデッセイ_千年の夢_重松_清.txt:
  name: 失落的奧德賽_千年之夢_永遠的旅人_永遠を旅する者_ロストオデッセイ_千年の夢_重松_清.txt
  path: 测试/testdir/失落的奧德賽_千年之夢_永遠的旅人_永遠を旅する者_ロストオデッセイ_千年の夢_重松_清.txt
  md5: 96ca9b655d8ecd97a2b3dc83190dd245
急性氯化钡中毒致恶性心律失常、反复心脏骤停一例.pdf:
  name: 急性氯化钡中毒致恶性心律失常、反复心脏骤停一例.pdf
  path: 测试/急性氯化钡中毒致恶性心律失常、反复心脏骤停一例.pdf
  md5: ed339befd275d168da95616ee1c95ec1
测试.txt:
  name: 测试.txt
  path: 测试/测试.txt
  md5: 418e2c7fb040367d77776c3dbd200164
網文寫手古代生存錄_令狐BEYOND.txt:
  name: 網文寫手古代生存錄_令狐BEYOND.txt
  path: 测试/網文寫手古代生存錄_令狐BEYOND.txt
  md5: c72773e8e1f56d8def67814c6fa50d80
